###
POST {{host}}/api/menu-groups
Content-Type: application/json

{
  "name": "추천메뉴22"
}

##########################################
## 메뉴그룹에는 굵직하게 메뉴들이 있다.
## 상위에 MenuGroup 이 있고,
## 하위에 Menu 가 있다.
## FK 는 Menu 에 걸려있다.
## 두마리 메뉴/ 한마리 메뉴/ 순살파닭두마리메뉴/ 신메뉴
##########################################
GET {{host}}/api/menus-groups

###
