##########################################
## Product 를 Menu 에 등록시킨다.
## -- menuGroupId 를 통해 해당 메뉴가 어떤 메뉴 그룹에 소속되는지를 명시한다.
## -- productId 를 통해서 혼합한 단일 상품의 가격의 합이 새롭게 만든 메뉴의 합보다 더 비싼 경우는 에러가 발생한다.
##########################################
POST {{host}}/api/menus
Content-Type: application/json

{
  "name": "통구이+간장",
  "price": 20000,
  "menuGroupId": 4,
  "menuProducts": [
    {
      "productId": 4,
      "quantity": 1
    },
    {
      "productId": 5,
      "quantity": 1
    }
  ]
}

##########################################
## 현재 등록된 메뉴를 조회한다.
## 상품과 메뉴는 별개이다.
## - 상품을 메뉴에 등록시켜야 해당 메뉴에 상품이 올라간다.
##########################################
GET {{host}}/api/menus

###
