##########################################
## order 를 생성한다.
## - orderTable 의 empty 값이 false 여야 생성된다.
## - orderTable 은 어느 orderTable 인지 명시.
## - orderLineItems 는
##########################################
POST {{host}}/api/orders
Content-Type: application/json

{
  "orderTableId": 2,
  "orderLineItems": [
    {
      "menuId": 1,
      "quantity": 1
    }
  ]
}

##########################################
## order 목록을 조회한다.
##########################################
GET {{host}}/api/orders

###
PUT {{host}}/api/orders/1/order-status
Content-Type: application/json

{
  "orderStatus": "MEAL"
}

###
PUT {{host}}/api/orders/1/order-status
Content-Type: application/json

{
  "orderStatus": "COMPLETION"
}

###
