##########################################
## 상품을 등록한다.
##########################################
POST {{host}}/api/products
Content-Type: application/json

{
  "name": "고구마치킨",
  "price": 17001
}

##########################################
## 상품을 조회한다.
##########################################
GET {{host}}/api/products

###
