##########################################
## 상품을 등록한다.
## 아이디는 자동으로 등록된다.
## 그 외 payload 로 name / price 를 전송
##########################################
POST {{host}}/api/products
Content-Type: application/json

{
  "name": "고구마치킨",
  "price": 17001
}

##########################################
## 등록된 상품을 조회한다.
## 상품 아이디, 이름, 가격
##########################################
GET {{host}}/api/products

###
