##########################################
## 주문테이블을 전체를 조회한다.
##########################################
GET localhost:8080/api/tables


##########################################
## 특정 주문테이블의 empty 를 `true` 로 변경
##########################################
PUT localhost:8080/api/tables/1/empty
Content-Type: application/json

{
  "empty": true
}

##########################################
## 특정 주문테이블의 empty 를 `false` 로 변경
##########################################
PUT localhost:8080/api/tables/1/empty
Content-Type: application/json

{
  "empty": false
}

##########################################
## 특정 주문테이블의 게스트 수를 `N` 으로 변경한다.
##########################################
PUT {{host}}/api/tables/1/number-of-guests
Content-Type: application/json

{
  "numberOfGuests": 4
}

###
